### ISSUE TITLE
Content review follow ups

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#769]
| Section | Lead | PRs |
|---------|------|-----|
| [Data Storage](https://docs.blockstack.org/data-storage/overview) | @agraebe / @aulneau  | #781 |
| [Stacks Blockchain](https://docs.blockstack.org/stacks-blockchain/overview) | @agraebe | #781 |
| [Stacks Wallet](https://docs.blockstack.org/stacks-wallet/overview) | @yknl / @markmhx | https://github.com/blockstack/blockstack.org/issues/1160 |
| [Naming services](https://docs.blockstack.org/naming-services/overview) | @kantai | |
| [Storage hubs](https://docs.blockstack.org/storage-hubs/overview) | @aulneau / @reedrosenbluth   | |
| [Ecosystem](https://docs.blockstack.org/ecosystem/overview) | @agraebe | |
| [References](https://docs.blockstack.org/references/blockstack-cli) | @aulneau | |
| General | @agraebe | |

Clean up, re-structure, and update content as follows:

**Data Storage**
- [x] Merge data indexing into the data storage section (#781)

**Stacks Blockchain**
- [x] Overview: Intro is too complex  (#781)
- [x] Overview: Stacks 2.0 features should be explained purely technical  (#781)
- [x] Overview: Mining isn't explained  (#781)
- [x] Overview: STX mining –> Stacks Mining  (#781)
- [x] Overview: The feature section shouldn't describe the technical details but the benefits developer would get from utilizing it  (#781)
- [x] Overview: PoX description to include “Instead of spending energy, Stacks miners transfer Bitcoin to holders of Stacks Token (STX) to mine a block.”  (#781)

**Stacks Wallet**

```
- [x] Should assume the audience understands crypto basics (and link out to refs)
- [x] Should assume the Wallet will include most relevant user-facing instructions, minimizing the need for wallet docs
- [ ] Support uses this docs page: https://docs.blockstack.org/stacks-wallet/usage. Content needs to available somewhere too
- [ ] Should use this as product description and focus on use cases/tasks that users can accomplish
- [ ] Future, user-facing wallet docs can be on the https://wallet.blockstack.org/ page
- [ ] New wallet release should include documentation updates (including a migration guide). We can make the updates with the release
```
-> This is all being tracked essentially with https://github.com/blockstack/blockstack.org/issues/1160

**Naming services**
- [ ] Merge most of the content into new Stacks 1.0 category
- [ ] Tailor content towards main use cases as opposed to general knowledge transfer
- [ ] Need more input on Stacks 2.0 implementation (BNS will be based on contracts), no need to prioritize work now
- [ ] A lot of content needs to be updated with the BNS changes for Stacks 2.0
- [ ] BNS being based on contracts, an introduction to contracts / clarity will be helpful. This could include an explanation of the smart contract functions
- [ ] Comparison requires updates, should list handshake
- [ ] Important parts: setting up a registrar, creating subdomains & namespaces
- [ ] Should ask devs what types of content they’d need (Provica)
- [x] Should add a link to the Github repo: https://github.com/blockstack/blockstack-search-indexer (#781)
- [ ] Sudomain section needs rework
- [x] Should remove: https://docs.blockstack.org/naming-services/forks (duplicate), https://docs.blockstack.org/naming-services/build-profile-search-index  (#781)

**Storage hubs**
- [x] Remove “Hello world hub choice”  (#781)
- [x] Merge “Gaia admin” and “config schema” (#781)
- [ ] Important info for portability & ownership, call that out
- [x] Should move the deployed content into a new “tutorials” section (#781)
- [ ] Tutorials are very difficult, simplify?
- [ ] Rethink the naming. Ideas: Data ownership, Storage service
- [ ] Overview: should have an intro to 1) understand the process and 2) explain the options for the deployment
- [ ] Should make a note about deprecated mentions (e.g. Blockstack Browser)
- [ ] Ask Dan what he thinks about storage hubs
- [ ] Should revisit post mainnet and discuss the future of Gaia

**Ecosystem**
- [ ] Needs to be reviewed and updated

**References**
- [ ] Monorepo updates would impact the reference generation. Should review once that happens
- [x] Update https://docs.blockstack.org/references/language-clarity: missing string types (#781)
- [ ] First part (manual) of "language-clarity" could be updated automatically as well. Should create an issue in the blockchain repo
- [ ] Discussion: OpenAPI references: does it make sense to have these docs inside our documentation? Should review what automation option we have
- [x] https://docs.blockstack.org/references/stacks-rpc-api should be removed and instead redirect to the OpenAPI docs. The OpenAPI spec should cover all details (#781)

**General**
- [ ] Revisit information architecture. Maybe could be a bit more use-case driven?

**Comment by agraebe** [comment]
@yknl @lgalabru @aulneau @hstove @reedrosenbluth @zone117x as per our last discussion, please add your name next to the section you'd like to help with:

| Section | Lead |
|---------|------|
| [Data Storage](https://docs.blockstack.org/data-storage/overview) | @agraebe |
| [Stacks Blockchain](https://docs.blockstack.org/stacks-blockchain/overview) | |
| [Stacks Wallet](https://docs.blockstack.org/stacks-wallet/overview) | |
| [Naming services](https://docs.blockstack.org/naming-services/overview) | |
| [Storage hubs](https://docs.blockstack.org/storage-hubs/overview) | |
| [Ecosystem](https://docs.blockstack.org/ecosystem/overview) | @agraebe |
| [References](https://docs.blockstack.org/references/blockstack-cli) | |
| General | @agraebe |

**Comment by markmhx** [comment]
As discussed during the planning meeting yesterday, all improvements made by @yknl as part of this ticket and related to the Stacks Wallet should focus on the _current_ Stacks Wallet and not the creation of any content for the new / upcoming Stacks Wallet in development.

This ticket's work _should_ include any documentation updates needed to support upgrades to the current wallet, such as https://github.com/blockstack/stacks-wallet/issues/131.

Once revisions to the current Stacks Wallet documentation are complete as tracked by this issue, that user-facing documentation will get migrated to blockstack.org as separately tracked by https://github.com/blockstack/blockstack.org/issues/1160. @yknl please notify me when that's the case.

The content will then get reformatted as needed to support the release of the new Stacks Wallet as tracked by https://github.com/blockstack/stacks-wallet/issues/172.

**Comment by agraebe** [comment]
Sorry, noticed GH automatically closed this issue when I merged @aulneau @yknl @markmhx @reedrosenbluth @kantai. I only completed the structural changes and low hanging fruits in my first PR

**Comment by muneeb-ali** [comment]
Looks like a really comprehensive list! Some community members might be able to help here as well. Brad for example maintains https://stacks.zone and might be on top of some info.

**Comment by markmhx** [comment]
I'm removing my assignment since related Stacks Wallet here is now tracked with blockstack/blockstack.org#1160
